site_name: CppToday
site_description: A minimal C++23 project template that prints current date.
site_author: Aaron Fu Lei
site_url: https://aafulei.github.io/cpp-today

repo_name: cpp-today
repo_url: https://github.com/aafulei/cpp-today

copyright: Built by <a href="http://github.com/aafulei">Aaron</a> with ❤️

theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  logo: img/logo-mkdocs.svg
  favicon: img/icon.svg

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: getting-started.md
    - Testing: testing.md
    - Build System: build-system.md
  - Technical Details:
    - Single Source of Truth: single-source-of-truth.md
    - Makefile in Detail: makefile-in-detail.md
    - Ready for Deployment: ready-for-deployment.md
  - Code Reference: doxygen/html/index.html

plugins:
  - search

extra_css:
  - css/custom-mkdocs.css
